
.meas tr th1  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=1  
.meas tr th2  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=2  
.meas tr th3  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=3  
.meas tr th4  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=4  
.meas tr th5  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=5  
.meas tr th6  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=6  
.meas tr th7  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=7  
.meas tr th8  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=8  
.meas tr th9  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=9  
.meas tr th10 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=10 
.meas tr th11 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=11 
.meas tr th12 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=12 
.meas tr th13 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=13 
.meas tr th14 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=14 
.meas tr th15 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=15 
.meas tr th16 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=16 
.meas tr th17 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=17 
.meas tr th18 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=18 
.meas tr th19 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=19 
.meas tr th20 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 rise=20 

.meas tr tl1  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=1  
.meas tr tl2  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=2  
.meas tr tl3  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=3  
.meas tr tl4  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=4  
.meas tr tl5  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=5  
.meas tr tl6  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=6  
.meas tr tl7  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=7  
.meas tr tl8  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=8  
.meas tr tl9  trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=9  
.meas tr tl10 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=10 
.meas tr tl11 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=11 
.meas tr tl12 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=12 
.meas tr tl13 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=13 
.meas tr tl14 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=14 
.meas tr tl15 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=15 
.meas tr tl16 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=16 
.meas tr tl17 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=17 
.meas tr tl18 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=18 
.meas tr tl19 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=19 
.meas tr tl20 trig V(ck) = 'VDD/2' rise=1 targ V(vop_conv, von_conv) = 0 fall=20 

.meas tr th2_1  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=1  
.meas tr th2_2  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=2  
.meas tr th2_3  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=3  
.meas tr th2_4  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=4  
.meas tr th2_5  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=5  
.meas tr th2_6  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=6  
.meas tr th2_7  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=7  
.meas tr th2_8  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=8  
.meas tr th2_9  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=9  
.meas tr th2_10 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=10 
.meas tr th2_11 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=11 
.meas tr th2_12 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=12 
.meas tr th2_13 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=13 
.meas tr th2_14 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=14 
.meas tr th2_15 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=15 
.meas tr th2_16 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=16 
.meas tr th2_17 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=17 
.meas tr th2_18 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=18 
.meas tr th2_19 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=19 
.meas tr th2_20 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 rise=20 

.meas tr tl2_1  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=1  
.meas tr tl2_2  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=2  
.meas tr tl2_3  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=3  
.meas tr tl2_4  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=4  
.meas tr tl2_5  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=5  
.meas tr tl2_6  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=6  
.meas tr tl2_7  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=7  
.meas tr tl2_8  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=8  
.meas tr tl2_9  trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=9  
.meas tr tl2_10 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=10 
.meas tr tl2_11 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=11 
.meas tr tl2_12 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=12 
.meas tr tl2_13 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=13 
.meas tr tl2_14 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=14 
.meas tr tl2_15 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=15 
.meas tr tl2_16 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=16 
.meas tr tl2_17 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=17 
.meas tr tl2_18 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=18 
.meas tr tl2_19 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=19 
.meas tr tl2_20 trig V(ck) = 'VDD/2' rise=1 targ V(vop_htr, von_htr) = 0 fall=20 

.meas tr th3_1  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=1  
.meas tr th3_2  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=2  
.meas tr th3_3  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=3  
.meas tr th3_4  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=4  
.meas tr th3_5  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=5  
.meas tr th3_6  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=6  
.meas tr th3_7  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=7  
.meas tr th3_8  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=8  
.meas tr th3_9  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=9  
.meas tr th3_10 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=10 
.meas tr th3_11 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=11 
.meas tr th3_12 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=12 
.meas tr th3_13 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=13 
.meas tr th3_14 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=14 
.meas tr th3_15 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=15 
.meas tr th3_16 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=16 
.meas tr th3_17 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=17 
.meas tr th3_18 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=18 
.meas tr th3_19 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=19 
.meas tr th3_20 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 rise=20 

.meas tr tl3_1  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=1  
.meas tr tl3_2  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=2  
.meas tr tl3_3  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=3  
.meas tr tl3_4  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=4  
.meas tr tl3_5  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=5  
.meas tr tl3_6  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=6  
.meas tr tl3_7  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=7  
.meas tr tl3_8  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=8  
.meas tr tl3_9  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=9  
.meas tr tl3_10 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=10 
.meas tr tl3_11 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=11 
.meas tr tl3_12 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=12 
.meas tr tl3_13 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=13 
.meas tr tl3_14 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=14 
.meas tr tl3_15 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=15 
.meas tr tl3_16 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=16 
.meas tr tl3_17 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=17 
.meas tr tl3_18 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=18 
.meas tr tl3_19 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=19 
.meas tr tl3_20 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh, von_sh) = 0 fall=20 

.meas tr th6_1  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=1  
.meas tr th6_2  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=2  
.meas tr th6_3  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=3  
.meas tr th6_4  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=4  
.meas tr th6_5  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=5  
.meas tr th6_6  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=6  
.meas tr th6_7  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=7  
.meas tr th6_8  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=8  
.meas tr th6_9  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=9  
.meas tr th6_10 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=10 
.meas tr th6_11 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=11 
.meas tr th6_12 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=12 
.meas tr th6_13 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=13 
.meas tr th6_14 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=14 
.meas tr th6_15 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=15 
.meas tr th6_16 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=16 
.meas tr th6_17 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=17 
.meas tr th6_18 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=18 
.meas tr th6_19 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=19 
.meas tr th6_20 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 rise=20 

.meas tr tl6_1  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=1  
.meas tr tl6_2  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=2  
.meas tr tl6_3  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=3  
.meas tr tl6_4  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=4  
.meas tr tl6_5  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=5  
.meas tr tl6_6  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=6  
.meas tr tl6_7  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=7  
.meas tr tl6_8  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=8  
.meas tr tl6_9  trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=9  
.meas tr tl6_10 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=10 
.meas tr tl6_11 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=11 
.meas tr tl6_12 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=12 
.meas tr tl6_13 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=13 
.meas tr tl6_14 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=14 
.meas tr tl6_15 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=15 
.meas tr tl6_16 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=16 
.meas tr tl6_17 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=17 
.meas tr tl6_18 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=18 
.meas tr tl6_19 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=19 
.meas tr tl6_20 trig V(ck) = 'VDD/2' rise=1 targ V(vop_dbt, von_dbt) = 0 fall=20 

.meas tr th4_1  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=1  
.meas tr th4_2  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=2  
.meas tr th4_3  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=3  
.meas tr th4_4  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=4  
.meas tr th4_5  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=5  
.meas tr th4_6  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=6  
.meas tr th4_7  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=7  
.meas tr th4_8  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=8  
.meas tr th4_9  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=9  
.meas tr th4_10 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=10 
.meas tr th4_11 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=11 
.meas tr th4_12 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=12 
.meas tr th4_13 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=13 
.meas tr th4_14 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=14 
.meas tr th4_15 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=15 
.meas tr th4_16 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=16 
.meas tr th4_17 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=17 
.meas tr th4_18 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=18 
.meas tr th4_19 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=19 
.meas tr th4_20 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 rise=20 

.meas tr tl4_1  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=1  
.meas tr tl4_2  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=2  
.meas tr tl4_3  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=3  
.meas tr tl4_4  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=4  
.meas tr tl4_5  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=5  
.meas tr tl4_6  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=6  
.meas tr tl4_7  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=7  
.meas tr tl4_8  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=8  
.meas tr tl4_9  trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=9  
.meas tr tl4_10 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=10 
.meas tr tl4_11 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=11 
.meas tr tl4_12 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=12 
.meas tr tl4_13 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=13 
.meas tr tl4_14 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=14 
.meas tr tl4_15 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=15 
.meas tr tl4_16 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=16 
.meas tr tl4_17 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=17 
.meas tr tl4_18 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=18 
.meas tr tl4_19 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=19 
.meas tr tl4_20 trig V(ck) = 'VDD/2' rise=1 targ V(vop_single, von_single) = 0 fall=20 

.meas tr th5_1  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=1  
.meas tr th5_2  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=2  
.meas tr th5_3  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=3  
.meas tr th5_4  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=4  
.meas tr th5_5  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=5  
.meas tr th5_6  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=6  
.meas tr th5_7  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=7  
.meas tr th5_8  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=8  
.meas tr th5_9  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=9  
.meas tr th5_10 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=10 
.meas tr th5_11 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=11 
.meas tr th5_12 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=12 
.meas tr th5_13 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=13 
.meas tr th5_14 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=14 
.meas tr th5_15 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=15 
.meas tr th5_16 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=16 
.meas tr th5_17 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=17 
.meas tr th5_18 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=18 
.meas tr th5_19 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=19 
.meas tr th5_20 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 rise=20 

.meas tr tl5_1  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=1  
.meas tr tl5_2  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=2  
.meas tr tl5_3  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=3  
.meas tr tl5_4  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=4  
.meas tr tl5_5  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=5  
.meas tr tl5_6  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=6  
.meas tr tl5_7  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=7  
.meas tr tl5_8  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=8  
.meas tr tl5_9  trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=9  
.meas tr tl5_10 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=10 
.meas tr tl5_11 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=11 
.meas tr tl5_12 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=12 
.meas tr tl5_13 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=13 
.meas tr tl5_14 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=14 
.meas tr tl5_15 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=15 
.meas tr tl5_16 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=16 
.meas tr tl5_17 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=17 
.meas tr tl5_18 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=18 
.meas tr tl5_19 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=19 
.meas tr tl5_20 trig V(ck) = 'VDD/2' rise=1 targ V(vop_sh_s2d, von_sh_s2d) = 0 fall=20 

